title = "Gerold Busch"

[languages]
  [languages.en]
    languageCode = "en"
    languageName = "English"
    displayName = "EN"
    isoCode = "en"
    weight = 1
    rtl = false

    title = "Gerold Busch"
    # logo = "img/logo.jpg"
    description = "Gerold Busch's website"
    copyright = "(c) Gerold Busch, 2024"

    dateFormat = "2 January 2006"
